buffer_size: [ 100000 ]
target_update_interval: [ 2000 ]
gamma: [ 0.9, 0.99 ]
train_eps: [ 0.01 ] #, 0.05]
batch_size: [ 32, 64 ] #[32, 64, 128, 256]
learning_rate: [ 0.0001 ] #, 0.0005, 0.001]
reward_weights: # ['load_balance', 'op_cost', 'waiting_time', 'queue_occ', 'queue_drop_rate', 'free_capacity']
  - [ 1,1,1 ]
  - [0.25, 0.5, 1]
#  - [ 1,1,2]
#  - [ 1,2,1]
#  - [ 1,2,2]