drl_algo: [ 'TD3' ]
learning_starts: [ 5000 ]
buffer_size: [ 100000 ]
batch_size: [ 512 ] #[32, 64, 128, 256]
learning_rate: [ 0.0001 ] #, 0.0005, 0.001]
action_noise_sigma: [ 0.1, 0.2 ]
mlp_arch:
  - [ 32, 32, 32 ]
  - [ 16, 16, 16 ]
  #- [ 64, 32, 32 ]
reward_weights: # ['load_balance', 'op_cost', 'waiting_time']
  - [ 0.5,0.5,1 ]
  - [ 0.25,0.5,1 ]
  - [ 1,1,1 ]
#  - [ 1,1,2]
#  - [ 1,2,1]
#  - [ 1,2,2]