learning_starts: [ 10000 ]
buffer_size: [ 100000 ]
target_update_interval: [ 1008 ]
gamma: [ 0.99 ]
exploration_final_eps: [ 0.01 ] #, 0.05]
batch_size: [ 256 ] #[32, 64, 128, 256]
learning_rate: [ 0.0001 ] #, 0.0005, 0.001]
train_freq: [ 4 ]
reward_weights: # ['load_balance', 'op_cost', 'waiting_time', 'queue_occ', 'queue_drop_rate', 'free_capacity']
  - [ 1,1,1,0,0,0 ]
  - [ 1,1,2,0,0,0 ]
  - [ 1,2,1,0,0,0 ]
  - [ 1,2,2,0,0,0 ]