learning_starts: [10000]
buffer_size: [100000]
target_update_interval: [504, 1008]
gamma:  [0.99]
exploration_final_eps: [0.01, 0.05]
batch_size: [32, 64, 128, 256]
learning_rate: [0.0001, 0.0005, 0.001]
train_freq: [4]