drl_algo: [ 'DQN','DDQN' ]
learning_starts: [ 5000 ]
buffer_size: [ 100000 ]
target_update_interval: [ 2000 ]
gamma: [ 0.99 ]
exploration_fraction: [ 0.7 ]
exploration_final_eps: [ 0.01 ] #, 0.05]
batch_size: [ 128 ] #[32, 64, 128, 256]
learning_rate: [ 0.0001 ] #, 0.0005, 0.001]
train_freq: [ 2, 4 ]
reward_weights: # ['load_balance', 'op_cost', 'waiting_time', 'queue_occ', 'queue_drop_rate', 'free_capacity']
  - [ 1,1,1 ]
#  - [ 1,1,2]
#  - [ 1,2,1]
#  - [ 1,2,2]