buffer_size: [ 100000 ]
target_update_interval: [ 2000 ]
gamma: [ 0.9 ]
train_each_n_step: [4]
train_eps: [ 0.1 ] #, 0.05]
batch_size: [ 64 ] #[32, 64, 128, 256]
learning_rate: [ 0.0005] #, 0.0005, 0.001]
layer_dim: [ 64 ]
num_layers: [ 2 ]
reward_weights: # ['load_balance', 'op_cost', 'waiting_time', 'queue_occ', 'queue_drop_rate', 'free_capacity']
    - [0.25, 0.5, 1]
    - [1, 1, 1]
    - [0.5, 0.5, 1]
    - [0.5, 1, 1]